version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: sh -c "rm -rf /app/tmp/pids/server.pid && bundle exec rails db:setup && foreman start"
    environment:
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - .:/app
    ports:
      - "1080:1080"
      - "3000:3000"
    depends_on:
      - db
