version: 2
jobs:
  build:
    working_directory: ~/michigan-benefits

    docker:
      - image: circleci/ruby:2.5.1-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
          RACK_ENV: test

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test

    steps:
      - checkout

      - restore_cache:
          keys:
            - michigan-benefits-{{ checksum "Gemfile.lock" }}
            - michigan-benefits-

      - run:
          name: Install dependencies
          command: sudo apt-get update; sudo apt-get install pdftk libmagic-dev nodejs

      - run:
          name: Install gem dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          key: michigan-benefits-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:test:prepare

#      - run: bundle exec bundle-audit update && bundle exec bundle-audit check
#      - run: bundle exec brakeman
#      - run: bundle exec rubocop

      - run:
          name: Parallel RSpec
          command: bin/rails spec

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results

#      - run: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
#      - run: git push git@heroku.com:michigan-benefits-staging.git $CIRCLE_SHA1:refs/heads/master
