version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-browsers
    working_directory: ~/michigan-benefits
    steps:
      - checkout

      - restore_cache:
          keys:
            - benefits-bundler-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: sudo apt-get update; sudo apt-get install pdftk libmagic-dev

      - run:
          name: Install Bundler dependencies
          command: bundle install --deployment --retry=3

      - save_cache:
          key: benefits-bundler-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            # the --deployment flag tells bundler to install here
            - vendor/bundle

#      - run: bundle exec bundle-audit update && bundle exec bundle-audit check
#      - run: bundle exec brakeman
#      - run: bundle exec rubocop

      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --format progress

#      - run: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
#      - run: git push git@heroku.com:michigan-benefits-staging.git $CIRCLE_SHA1:refs/heads/master
