version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-browsers
    steps:
      - checkout
      - run: sudo apt-get update; sudo apt-get install pdftk

  check:
    machine: true
    steps:
      - run: bundle exec bundle-audit update && bundle exec bundle-audit check
      - run: bundle exec brakeman

  lint:
    machine: true
    steps:
      - run: rubocop

  test:
    machine: true
    steps:
      - run: RAILS_ENV=test bundle exec rspec

  deploy-staging:
    machine: true
    steps:
      - run: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - run: git push git@heroku.com:michigan-benefits-staging.git $CIRCLE_SHA1:refs/heads/master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /WIP-.*/
                - /wip-.*/
      - check:
          requires:
            - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy-staging:
          requires:
            - check
            - lint
            - test
          filters:
            branches:
              only: master
