require "rails_helper"

RSpec.describe SnapApplicationAttributes do
  describe "#to_h" do
    it "returns a hash of attributes" do
      mailing_address = build(
        :mailing_address,
        street_address_2: "Apt B",
        county: "Genessee",
      )
      snap_application = create(
        :snap_application,
        :with_member,
        addresses: [mailing_address],
        financial_accounts: [:four_oh_one_k],
        phone_number: "2024561111",
        rent_expense: 100,
        property_tax_expense: 0,
        insurance_expense: 0,
        stable_housing: false,
        authorized_representative: true,
        authorized_representative_name: "aBenny",
      )

      member = snap_application.members.first
      member.update(buy_food_with: false)

      data =
        SnapApplicationAttributes.new(snap_application: snap_application).to_h

      expect(data).to eq(
        additional_income_child_support: nil,
        additional_income_no: "Yes",
        additional_income_other: nil,
        additional_income_pension: nil,
        additional_income_social_security: nil,
        additional_income_ssi: nil,
        additional_income_unemployment: nil,
        additional_income_workers_compensation: nil,
        annual_insurance_expense: nil,
        annual_property_tax_expense: nil,
        applying_for_food_assistance: "Yes",
        authorized_representative_name: "aBenny",
        authorized_representative_yes: "Yes",
        care_expenses_childcare: nil,
        care_expenses_disabled: nil,
        care_expenses_interval: nil,
        court_ordered_expenses_alimony: nil,
        court_ordered_expenses_child_support: nil,
        court_ordered_expenses_interval: nil,
        court_ordered_expenses_no: "Yes",
        dependent_care_no: "Yes",
        email: "test@example.com",
        employed_household_members_no: "Yes",
        financial_accounts_checking_or_savings_account: nil,
        financial_accounts_four_oh_one_k_or_iras: "Yes",
        financial_accounts_life_insurance: nil,
        financial_accounts_mutual_funds_or_stocks: nil,
        financial_accounts_other: nil,
        financial_accounts_trusts: nil,
        first_member_with_disability_name: nil,
        homeless_yes: "Yes",
        income_change_explanation: nil,
        income_change_no: "Yes",
        insurance_expense_yes: nil,
        mailing_address_city: "Flint",
        mailing_address_county: "Genessee",
        mailing_address_state: "MI",
        mailing_address_street_address: "123 Main St., Apt B",
        mailing_address_zip: "12345",
        medical_expenses_dental: nil,
        medical_expenses_health_insurance: nil,
        medical_expenses_hospital_bills: nil,
        medical_expenses_no: "Yes",
        medical_expenses_other: nil,
        medical_expenses_prescriptions: nil,
        medical_expenses_transportation: nil,
        members_buy_food_with_no: "Yes",
        members_not_buy_food_with: member.display_name,
        members_with_disability_no: "Yes",
        monthly_additional_income: nil,
        monthly_care_expenses: nil,
        monthly_court_ordered_expenses: nil,
        monthly_gross_income: snap_application.monthly_gross_income,
        monthly_medical_expenses: nil,
        monthly_rent_taxes_and_insurance: 100,
        more_than_six_members_no: "Yes",
        more_than_two_employed_no: "Yes",
        more_than_two_self_employed_no: "Yes",
        mortgage_expense: nil,
        mortgage_expense_interval: nil,
        mortgage_expense_yes: nil,
        phone_number_0: "2",
        phone_number_1: "0",
        phone_number_2: "2",
        phone_number_3: "4",
        phone_number_4: "5",
        phone_number_5: "6",
        phone_number_6: "1",
        phone_number_7: "1",
        phone_number_8: "1",
        phone_number_9: "1",
        property_tax_expense_yes: nil,
        rent_expense: 100,
        rent_expense_interval: "Yes",
        rent_expense_yes: "Yes",
        residential_address_city: nil,
        residential_address_county: nil,
        residential_address_state: nil,
        residential_address_street_address: "Homeless",
        residential_address_zip: "12345",
        second_member_with_disability_name: nil,
        self_employed_household_members_no: "Yes",
        signature: "Mr. RJD2",
        signature_date: snap_application.signed_at_est,
        third_member_with_disability_name: nil,
        total_money: snap_application.total_money,
        utility_cooling_no: "Yes",
        utility_electricity: nil,
        utility_heat_no: "Yes",
        utility_other: nil,
        utility_phone: nil,
        utility_trash: nil,
        utility_water_sewer: nil,
        vehicle_income_no: "Yes",
      )
    end
  end
end
